# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-22 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='website',
        ),
        migrations.AddField(
            model_name='lead',
            name='casetype',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Case Type'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('previous client', 'Previous Client'), ('friends family', 'Friends / Family'), ('website', 'Website'), ('compaign', 'Campaign'), ('other', 'Other')], max_length=255, null=True, verbose_name='Source of Lead'),
        ),
    ]
