# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-27 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20171123_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('Wmail', 'Email'), ('Previous Client', 'Previous Client'), ('Friends or Family', 'Friends / Family'), ('Website', 'Website'), ('Campaign', 'Campaign'), ('Other', 'Other')], max_length=255, null=True, verbose_name='Source of Lead'),
        ),
    ]
