# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-27 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20170926_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, choices=[('CRIMINAL', 'CRIMINAL'), ('CIVIL NEGLIGENCE', 'CIVIL NEGLIGENCE'), ('FAMILY', 'FAMILY'), ('CIVIL OTHER', 'CIVIL OTHER')], default='', max_length=255, null=True),
        ),
    ]
