# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-28 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20171128_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='closed_on',
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
