# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-27 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20170926_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='industry',
            field=models.CharField(blank=True, choices=[('CRIMINAL', 'CRIMINAL'), ('CIVIL NEGLIGENCE', 'CIVIL NEGLIGENCE'), ('FAMILY', 'FAMILY'), ('CIVIL OTHER', 'CIVIL OTHER')], max_length=255, null=True, verbose_name='Industry Type'),
        ),
    ]
